version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    networks:
        - laraveldockerize

  #MySQL Service
  mysql:
        image: mysql:8.0.25
        container_name: mysql2-uc
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: egame
            MYSQL_ROOT_PASSWORD : abao3023
            SERVICE_TAG: dev
            SERVICE_NAME: mysql
        networks:
            - laraveldockerize


  #PHP Service
  php:
    build:
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    container_name: lcp_php
    volumes: 
      - .:/var/www/html
    ports: 
      - "9000:9000"
    networks:
      - laraveldockerize 

  #Composer Service
  composer:
    image: composer:latest
    container_name: lcp_composer
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks:
      - laraveldockerize    

  #NPM Service
  npm:
    image: node:14.9
    container_name: lcp_npm
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  #Artisan Service
  artisan:
    build: 
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    container_name: lcp_artisan
    volumes: 
      - .:/var/www/html
    depends_on: 
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laraveldockerize


#Docker Networks
networks:
  laraveldockerize: