version: "3.8"
  
services:

  #Apache
  app:
    build:
      context: .
      dockerfile: ./dockerize/Dockerfile
    image: 'laravelapp'
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html


    networks:
      - laraveldockerize

  #MySQL Service
  mysql:
        image: mysql:8.0.25
        container_name: mysql2-uc
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: egame
            MYSQL_ROOT_PASSWORD : abao3023
            SERVICE_TAG: dev
            SERVICE_NAME: mysql
        networks:
            - laraveldockerize


  #PHP Service
  php:
    build:
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    container_name: lcp_php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laraveldockerize

  #Composer Service
  composer:
    image: composer:latest
    container_name: lcp_composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laraveldockerize
